/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package emanager1.pkg0;

import emanager1.pkg0.ConformDialog;
import emanager1.pkg0.ConformDialog;
import emanager1.pkg0.MainMenu;
import emanager1.pkg0.MainMenu;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;

/**
 *
 * @author smbha
 */
public class EmployeeOperations extends javax.swing.JFrame {

    private static final String username = "root";
    private static final String password = "";
    private static final String dataConn = "jdbc:mysql://localhost:3306/emanager";

    Connection sqlConn = null;
    PreparedStatement pst = null;

    /**
     * Creates new form AddEmployeeForm
     */
    public EmployeeOperations() {
        this.setResizable(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        epfnol = new javax.swing.JLabel();
        epfnof = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        namef = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        contactnof = new javax.swing.JTextField();
        emailf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        bankaccnof = new javax.swing.JTextField();
        addressf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        userlbl = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        nicnof = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        departmentf = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        designationf = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        yearf = new javax.swing.JTextField();
        monthf = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        dayf = new javax.swing.JComboBox<>();
        salaryf = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        genderf = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        titlelbl = new javax.swing.JLabel();
        epfnos = new javax.swing.JTextField();
        searchb = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("EPF No.");

        jTextField7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setForeground(new java.awt.Color(51, 51, 51));

        epfnol.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        epfnol.setForeground(new java.awt.Color(255, 255, 255));
        epfnol.setText("EPF No");

        epfnof.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        epfnof.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        epfnof.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        epfnof.setPreferredSize(new java.awt.Dimension(64, 30));
        epfnof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                epfnofActionPerformed(evt);
            }
        });
        epfnof.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                epfnofKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");

        namef.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        namef.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        namef.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        namef.setPreferredSize(new java.awt.Dimension(64, 30));
        namef.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                namefKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Contact No");

        contactnof.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        contactnof.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        contactnof.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        contactnof.setPreferredSize(new java.awt.Dimension(64, 30));
        contactnof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactnofActionPerformed(evt);
            }
        });
        contactnof.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                contactnofKeyPressed(evt);
            }
        });

        emailf.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        emailf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        emailf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        emailf.setPreferredSize(new java.awt.Dimension(64, 30));
        emailf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailfActionPerformed(evt);
            }
        });
        emailf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emailfKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Bank Acc No");

        bankaccnof.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        bankaccnof.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bankaccnof.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        bankaccnof.setPreferredSize(new java.awt.Dimension(64, 30));
        bankaccnof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankaccnofActionPerformed(evt);
            }
        });
        bankaccnof.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bankaccnofKeyPressed(evt);
            }
        });

        addressf.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        addressf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        addressf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        addressf.setPreferredSize(new java.awt.Dimension(64, 30));
        addressf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressfActionPerformed(evt);
            }
        });
        addressf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addressfKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Address");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel17)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2)
                    .addComponent(epfnol)
                    .addComponent(jLabel7))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addressf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contactnof, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(bankaccnof, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emailf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(namef, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(epfnof, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(epfnol)
                    .addComponent(epfnof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactnof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(bankaccnof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jButton7.setBackground(new java.awt.Color(0, 153, 0));
        jButton7.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Logged As");
        jButton7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jButton7.setBorderPainted(false);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.setFocusPainted(false);
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton7MouseExited(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        userlbl.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        userlbl.setForeground(new java.awt.Color(204, 204, 204));
        userlbl.setText("userType");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/closer.png"))); // NOI18N
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setForeground(new java.awt.Color(51, 51, 51));

        jButton1.setBackground(new java.awt.Color(51, 78, 89));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add Empoyee");
        jButton1.setToolTipText("");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(51, 78, 89));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Clear");
        jButton3.setToolTipText("");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jButton3.setBorderPainted(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(51, 78, 89));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Update");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jButton5.setBorderPainted(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton5MouseExited(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(51, 78, 89));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Delete");
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jButton6.setBorderPainted(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton6MouseExited(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setForeground(new java.awt.Color(51, 51, 51));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText(" NIC No");

        nicnof.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        nicnof.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nicnof.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        nicnof.setPreferredSize(new java.awt.Dimension(64, 30));
        nicnof.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nicnofKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Department");

        departmentf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        departmentf.setMaximumRowCount(20);
        departmentf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(none)", "HR", "Finance", "Sales", "Marketing", "Operations", "Customer Support", "IT", "Legal", "R&D", "Admin" }));
        departmentf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        departmentf.setPreferredSize(new java.awt.Dimension(151, 30));
        departmentf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentfActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Salary");

        designationf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        designationf.setMaximumRowCount(20);
        designationf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(none)", "Manager", "Assistant", "Team Leader", "Specialist", "Analyst", "Administrator", "Consultant", "Technician", "Officer", "Executive", "Engineer", "Designer", "Salesperson", "Researcher" }));
        designationf.setToolTipText("");
        designationf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        designationf.setPreferredSize(new java.awt.Dimension(122, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Date Of Birth");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Year");

        yearf.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        yearf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        yearf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        yearf.setPreferredSize(new java.awt.Dimension(64, 30));

        monthf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        monthf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        monthf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        monthf.setPreferredSize(new java.awt.Dimension(72, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Month");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Day");

        dayf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dayf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        dayf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        dayf.setPreferredSize(new java.awt.Dimension(72, 30));

        salaryf.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        salaryf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        salaryf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        salaryf.setPreferredSize(new java.awt.Dimension(64, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Designation");

        genderf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        genderf.setMaximumRowCount(20);
        genderf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        genderf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        genderf.setMinimumSize(new java.awt.Dimension(81, 30));
        genderf.setPreferredSize(new java.awt.Dimension(81, 30));
        genderf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderfActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Gender");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(yearf, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(monthf, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(dayf, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel4))
                            .addComponent(jLabel16)
                            .addComponent(jLabel3)
                            .addComponent(jLabel15)
                            .addComponent(jLabel10)
                            .addComponent(jLabel14))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(departmentf, 0, 180, Short.MAX_VALUE)
                            .addComponent(designationf, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nicnof, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(salaryf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(genderf, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nicnof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(departmentf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(designationf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salaryf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(17, 17, 17)
                .addComponent(jLabel3)
                .addGap(5, 5, 5)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel18))
                .addGap(5, 5, 5)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(yearf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(monthf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dayf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(66, 66, 66));
        jPanel3.setForeground(new java.awt.Color(102, 102, 102));

        titlelbl.setFont(new java.awt.Font("Segoe UI", 1, 34)); // NOI18N
        titlelbl.setForeground(new java.awt.Color(224, 225, 223));
        titlelbl.setText("EMPLOYEE OPERATIONS");

        epfnos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        epfnos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        epfnos.setToolTipText("Enter EPF No. here");
        epfnos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        epfnos.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        epfnos.setPreferredSize(new java.awt.Dimension(64, 35));
        epfnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                epfnosActionPerformed(evt);
            }
        });
        epfnos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                epfnosKeyPressed(evt);
            }
        });

        searchb.setBackground(new java.awt.Color(0, 102, 0));
        searchb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        searchb.setForeground(new java.awt.Color(255, 255, 255));
        searchb.setText("Search");
        searchb.setToolTipText("");
        searchb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        searchb.setBorderPainted(false);
        searchb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchb.setPreferredSize(new java.awt.Dimension(59, 35));
        searchb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchbMouseExited(evt);
            }
        });
        searchb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(titlelbl)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(epfnos, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchb, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(epfnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(titlelbl))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 40, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(userlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121)
                .addComponent(jLabel11)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(userlbl)
                        .addComponent(jLabel1))
                    .addComponent(jLabel11))
                .addGap(30, 30, 30)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(28, 28, 28))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));
        jPanel6.setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void contactnofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactnofActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactnofActionPerformed

    private void emailfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailfActionPerformed

    private void epfnofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_epfnofActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_epfnofActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String genderType = (String) genderf.getSelectedItem();
        String deptType = (String) departmentf.getSelectedItem();
        String designationType = (String) designationf.getSelectedItem();
        Integer bmonth = Integer.valueOf((String) monthf.getSelectedItem());
        Integer bday = Integer.valueOf((String) dayf.getSelectedItem());

        try {
            // Check if any of the fields are empty
            if (epfnof.getText().isEmpty() || namef.getText().isEmpty() || contactnof.getText().isEmpty()
                    || emailf.getText().isEmpty() || genderType.isEmpty() || bankaccnof.getText().isEmpty()
                    || deptType.isEmpty() || nicnof.getText().isEmpty() || addressf.getText().isEmpty()
                    || salaryf.getText().isEmpty() || designationType.isEmpty() || yearf.getText().isEmpty()) {

                JOptionPane.showMessageDialog(this, "Please fill in all fields.");
            } else {
                Class.forName("com.mysql.jdbc.Driver");
                sqlConn = DriverManager.getConnection(dataConn, username, password);

                pst = sqlConn.prepareStatement("INSERT INTO employeedata(epfno, name, contactno, email, gender, bankaccno, department, nic, address, salary, designation, bdate) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
                pst.setString(1, epfnof.getText());
                pst.setString(2, namef.getText());
                pst.setString(3, contactnof.getText());
                pst.setString(4, emailf.getText());
                pst.setString(5, genderType);
                pst.setString(6, bankaccnof.getText());
                pst.setString(7, deptType);
                pst.setString(8, nicnof.getText());
                pst.setString(9, addressf.getText());
                pst.setDouble(10, Double.parseDouble(salaryf.getText()));
                pst.setString(11, designationType);

                // Construct a java.sql.Date object from the year, month, and day values
                int year = Integer.parseInt(yearf.getText());
                Date bdate = new Date(year - 1900, bmonth - 1, bday);

                pst.setDate(12, bdate);

                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Record Added");
                clearAll();
            }
        } catch (HeadlessException | ClassNotFoundException | NumberFormatException | SQLException ex) {
            JOptionPane.showMessageDialog(this, "An error occurred: " + ex.getMessage());
        }

    }

    private String formatText(String text) {
        // Remove non-numeric characters
        text = text.replaceAll("[^0-9]", "");

        // Insert hyphens at the appropriate positions (after the 4th and 7th characters)
        if (text.length() >= 8) {
            text = text.substring(0, 4) + "-" + text.substring(4, 6) + "-" + text.substring(6, 8);
        } else if (text.length() >= 6) {
            text = text.substring(0, 4) + "-" + text.substring(4, 6);
        }

        return text;

    }//GEN-LAST:event_jButton1ActionPerformed

    private void departmentfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departmentfActionPerformed

    private void genderfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderfActionPerformed

    private void bankaccnofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bankaccnofActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bankaccnofActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        clearAll();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void searchbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbActionPerformed
        String epfno = epfnos.getText();

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/emanager", "root", "");
            PreparedStatement pstmt = conn.prepareStatement("SELECT * FROM employeedata WHERE epfno = ?");
            pstmt.setString(1, epfno);

            ResultSet rs = pstmt.executeQuery();

            if (rs.next()) {
                epfnof.setText(rs.getString("epfno"));
                namef.setText(rs.getString("name"));
                addressf.setText(rs.getString("address"));
                contactnof.setText(rs.getString("contactno"));
                emailf.setText(rs.getString("email"));
                bankaccnof.setText(rs.getString("bankaccno"));
                salaryf.setText(rs.getString("salary"));
                nicnof.setText(rs.getString("nic"));

                String department = rs.getString("department");
                setSelectedItem(departmentf, department);

                String gender = rs.getString("gender");
                setSelectedItem(genderf, gender);

                String designation = rs.getString("designation");
                setSelectedItem(designationf, designation);

                // Retrieve the bdate from the database
                Date bdate = rs.getDate("bdate");

                if (bdate != null) {
                    // Extract the year, month, and day from the bdate
                    Calendar cal = Calendar.getInstance();
                    cal.setTime(bdate);
                    int year = cal.get(Calendar.YEAR);
                    int month = cal.get(Calendar.MONTH) + 1; // Note: Calendar.MONTH is zero-based
                    int day = cal.get(Calendar.DAY_OF_MONTH);

                    // Set the values in the respective fields
                    yearf.setText(String.valueOf(year));
                    setSelectedItem(monthf, String.valueOf(month));
                    setSelectedItem(dayf, String.valueOf(day));
                } else {
                    // Handle the case where bdate is null
                    JOptionPane.showMessageDialog(this, "No date of birth found for EPF number: " + epfno, "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                // Handle the case where no user with the provided EPF number is found
                JOptionPane.showMessageDialog(this, "User not found.", "Error", JOptionPane.ERROR_MESSAGE);
            }

            rs.close();
            pstmt.close();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "User not found.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_searchbActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String epfno = epfnos.getText();

        String genderType = (String) genderf.getSelectedItem();
        String deptType = (String) departmentf.getSelectedItem();
        String designationType = (String) designationf.getSelectedItem();
        Integer bmonth = Integer.valueOf((String) monthf.getSelectedItem());
        Integer bday = Integer.valueOf((String) dayf.getSelectedItem());

        try {
            sqlConn = DriverManager.getConnection(dataConn, username, password);

            // Construct a java.sql.Date object from the year, month, and bday values
            int year = Integer.parseInt(yearf.getText());
            Date bdate = new Date(year - 1900, bmonth - 1, bday);

            String updateQuery = "UPDATE employeedata SET name=?, contactno=?, email=?, gender=?, bankaccno=?, department=?, nic=?, address=?, salary=?, designation=?, bdate=? WHERE epfno=?";

            pst = sqlConn.prepareStatement(updateQuery);
            pst.setString(1, namef.getText());
            pst.setString(2, contactnof.getText());
            pst.setString(3, emailf.getText());
            pst.setString(4, genderType);
            pst.setString(5, bankaccnof.getText());
            pst.setString(6, deptType);
            pst.setString(7, nicnof.getText());
            pst.setString(8, addressf.getText());
            pst.setDouble(9, Double.parseDouble(salaryf.getText()));
            pst.setString(10, designationType);
            pst.setDate(11, bdate);
            pst.setString(12, epfno);

            int rowsUpdated = pst.executeUpdate();

            if (rowsUpdated > 0) {
                JOptionPane.showMessageDialog(this, "Record Updated");
                clearAll();
            } else {
                JOptionPane.showMessageDialog(this, "No records found for EPF number: " + epfno);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "SQL error: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String epfno = epfnos.getText();

        if (epfno.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter EPF Number");
            return; // Exit the method if EPF Number is empty
        }

        try {
            Class.forName("com.mysql.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataConn, username, password);

            // Ask for confirmation before deleting the record
            int confirmDelete = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this record?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);

            if (confirmDelete == JOptionPane.YES_OPTION) {
                pst = sqlConn.prepareStatement("DELETE FROM employeedata WHERE epfno=?");
                pst.setString(1, epfno);
                pst.executeUpdate();

                JOptionPane.showMessageDialog(this, "Record Deleted");
                clearAll();
            } else {
                // User canceled the deletion
                JOptionPane.showMessageDialog(this, "Deletion canceled.");
            }
        } catch (HeadlessException | ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(this, "An error occurred: " + ex.getMessage());
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void epfnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_epfnosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_epfnosActionPerformed

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        jButton3.setBackground(new Color(0, 51, 204));
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
        jButton3.setBackground(new Color(51, 78, 89));
    }//GEN-LAST:event_jButton3MouseExited

    private void jButton7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseEntered
        jButton7.setText("Logout");
        jButton7.setBackground(Color.RED);
    }//GEN-LAST:event_jButton7MouseEntered

    private void jButton7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseExited
        jButton7.setText("Logged As");
        jButton7.setBackground(new Color(0, 102, 0));
    }//GEN-LAST:event_jButton7MouseExited

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        ConformDialog.conformLogout(this);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void searchbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchbMouseEntered
        searchb.setBackground(new Color(10, 153, 0));
    }//GEN-LAST:event_searchbMouseEntered

    private void searchbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchbMouseExited
        searchb.setBackground(new Color(0, 102, 0));
    }//GEN-LAST:event_searchbMouseExited

    private void addressfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressfActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        ConformDialog.conformExit();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        jButton1.setBackground(new Color(0, 153, 0));
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        jButton1.setBackground(new Color(51, 78, 89));
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseEntered
        jButton5.setBackground(new Color(0, 102, 0));
    }//GEN-LAST:event_jButton5MouseEntered

    private void jButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseExited
        jButton5.setBackground(new Color(51, 78, 89));
    }//GEN-LAST:event_jButton5MouseExited

    private void jButton6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseEntered
        jButton6.setBackground(new Color(255, 0, 0));
    }//GEN-LAST:event_jButton6MouseEntered

    private void jButton6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseExited
        jButton6.setBackground(new Color(51, 78, 89));
    }//GEN-LAST:event_jButton6MouseExited

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
        ImageIcon icon = new ImageIcon(getClass().getResource("/images/closerl.png"));
        jLabel11.setIcon(icon);
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
        ImageIcon icon = new ImageIcon(getClass().getResource("/images/closer.png"));
        jLabel11.setIcon(icon);
    }//GEN-LAST:event_jLabel11MouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        MainMenu mn = new MainMenu();
        this.dispose();
        mn.show();
        mn.userlbl.setText("Manager");
        mn.titlelbl.setText("MANAGER MENU");
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        ImageIcon icon = new ImageIcon(getClass().getResource("/images/backl.png"));
        jLabel1.setIcon(icon);
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        ImageIcon icon = new ImageIcon(getClass().getResource("/images/back.png"));
        jLabel1.setIcon(icon);
    }//GEN-LAST:event_jLabel1MouseExited

    private void epfnofKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_epfnofKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            namef.requestFocusInWindow();
        }else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            namef.requestFocusInWindow();
        }
    }//GEN-LAST:event_epfnofKeyPressed

    private void namefKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_namefKeyPressed
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_ENTER -> contactnof.requestFocusInWindow();
            case KeyEvent.VK_DOWN -> contactnof.requestFocusInWindow();
            case KeyEvent.VK_UP -> epfnof.requestFocusInWindow();
            default -> {
            }
        }
    }//GEN-LAST:event_namefKeyPressed

    private void contactnofKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactnofKeyPressed
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_ENTER -> emailf.requestFocusInWindow();
            case KeyEvent.VK_DOWN -> emailf.requestFocusInWindow();
            case KeyEvent.VK_UP -> namef.requestFocusInWindow();
            default -> {
            }
        }
    }//GEN-LAST:event_contactnofKeyPressed

    private void emailfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailfKeyPressed
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_ENTER -> addressf.requestFocusInWindow();
            case KeyEvent.VK_DOWN -> addressf.requestFocusInWindow();
            case KeyEvent.VK_UP -> contactnof.requestFocusInWindow();
            default -> {
            }
        }
    }//GEN-LAST:event_emailfKeyPressed

    private void addressfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressfKeyPressed
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_ENTER -> bankaccnof.requestFocusInWindow();
            case KeyEvent.VK_DOWN -> bankaccnof.requestFocusInWindow();
            case KeyEvent.VK_UP -> emailf.requestFocusInWindow();
            default -> {
            }
        }
    }//GEN-LAST:event_addressfKeyPressed

    private void bankaccnofKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bankaccnofKeyPressed
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_ENTER -> nicnof.requestFocusInWindow();
            case KeyEvent.VK_DOWN -> nicnof.requestFocusInWindow();
            case KeyEvent.VK_UP -> addressf.requestFocusInWindow();
            default -> {
            }
        }
    }//GEN-LAST:event_bankaccnofKeyPressed

    private void epfnosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_epfnosKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            searchb.doClick();
        }
    }//GEN-LAST:event_epfnosKeyPressed

    private void nicnofKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nicnofKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            bankaccnof.requestFocusInWindow();
        }
    }//GEN-LAST:event_nicnofKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeOperations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeOperations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeOperations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeOperations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeOperations().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressf;
    private javax.swing.JTextField bankaccnof;
    private javax.swing.JTextField contactnof;
    private javax.swing.JComboBox<String> dayf;
    private javax.swing.JComboBox<String> departmentf;
    private javax.swing.JComboBox<String> designationf;
    private javax.swing.JTextField emailf;
    private javax.swing.JTextField epfnof;
    private javax.swing.JLabel epfnol;
    private javax.swing.JTextField epfnos;
    private javax.swing.JComboBox<String> genderf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JComboBox<String> monthf;
    private javax.swing.JTextField namef;
    private javax.swing.JTextField nicnof;
    private javax.swing.JTextField salaryf;
    private javax.swing.JButton searchb;
    public javax.swing.JLabel titlelbl;
    public javax.swing.JLabel userlbl;
    private javax.swing.JTextField yearf;
    // End of variables declaration//GEN-END:variables

    private void setEPFNo(String string) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void setContactNo(String string) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void setEmail(String string) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void clearAll() {
        epfnof.setText("");
        namef.setText("");
        contactnof.setText("");
        emailf.setText("");
        genderf.setSelectedIndex(0);
        bankaccnof.setText("");
        departmentf.setSelectedIndex(0);
        nicnof.setText("");
        addressf.setText("");
        salaryf.setText("");
        designationf.setSelectedIndex(0);
        yearf.setText("");
        monthf.setSelectedIndex(0);
        dayf.setSelectedIndex(0);
        epfnof.setVisible(true);
        epfnol.setVisible(true);
    }

    private void setSelectedItem(JComboBox<String> comboBox, String value) {
        for (int i = 0; i < comboBox.getItemCount(); i++) {
            if (value.equals(comboBox.getItemAt(i))) {
                comboBox.setSelectedIndex(i);
                break;
            }
        }
    }
}
