/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package emanager1.pkg0;
import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author smbha
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form hrManagerMenu
     */
    public MainMenu() {
        this.setResizable(false);
        initComponents();
    }
    Login login = new Login();
    SearchData searchdata = new SearchData();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        userlbl = new javax.swing.JLabel();
        searchb = new javax.swing.JButton();
        createaccountb = new javax.swing.JButton();
        empoperationsb = new javax.swing.JButton();
        titlelbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jButton2.setBackground(new java.awt.Color(0, 153, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Logged As");
        jButton2.setToolTipText("Click here to logout");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jButton2.setBorderPainted(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setDisplayedMnemonicIndex(0);
        jButton2.setFocusPainted(false);
        jButton2.setFocusable(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        userlbl.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        userlbl.setForeground(new java.awt.Color(153, 153, 153));
        userlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userlbl.setText("usertype");

        searchb.setBackground(new java.awt.Color(204, 204, 204));
        searchb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        searchb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/client-60.png"))); // NOI18N
        searchb.setText("Search Employee");
        searchb.setBorderPainted(false);
        searchb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchb.setFocusPainted(false);
        searchb.setMaximumSize(new java.awt.Dimension(330, 100));
        searchb.setMinimumSize(new java.awt.Dimension(330, 100));
        searchb.setPreferredSize(new java.awt.Dimension(330, 100));
        searchb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchbMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchbMouseExited(evt);
            }
        });
        searchb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbActionPerformed(evt);
            }
        });

        createaccountb.setBackground(new java.awt.Color(204, 204, 204));
        createaccountb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        createaccountb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/create-60.png"))); // NOI18N
        createaccountb.setText("Create User Account");
        createaccountb.setBorderPainted(false);
        createaccountb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createaccountb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                createaccountbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                createaccountbMouseExited(evt);
            }
        });
        createaccountb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createaccountbActionPerformed(evt);
            }
        });

        empoperationsb.setBackground(new java.awt.Color(204, 204, 204));
        empoperationsb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        empoperationsb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/employee-60.png"))); // NOI18N
        empoperationsb.setText("Employee Operations");
        empoperationsb.setBorderPainted(false);
        empoperationsb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        empoperationsb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empoperationsbMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                empoperationsbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                empoperationsbMouseExited(evt);
            }
        });
        empoperationsb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empoperationsbActionPerformed(evt);
            }
        });

        titlelbl.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        titlelbl.setForeground(new java.awt.Color(204, 204, 204));
        titlelbl.setText("userType Menu");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/closer.png"))); // NOI18N
        jLabel2.setToolTipText("Exit button");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        jLabel3.setToolTipText("Click here to go back");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userlbl)
                .addGap(97, 97, 97)
                .addComponent(jLabel2)
                .addGap(25, 25, 25))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titlelbl)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(createaccountb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(68, 68, 68)
                        .addComponent(empoperationsb, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(userlbl)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17)
                        .addComponent(titlelbl)
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(empoperationsb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(48, 48, 48)
                .addComponent(createaccountb, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void createaccountbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createaccountbActionPerformed
        CreateAccount addAccount = new CreateAccount();
        this.hide();
        addAccount.userlbl.setText("Manager");
        addAccount.show();
        addAccount.typeComboBox.removeItem("Manager");
    }//GEN-LAST:event_createaccountbActionPerformed

    private void searchbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbActionPerformed
        String userType = userlbl.getText();
        if (userType.equals("Manager")) {
            searchdata.userlbl.setText(userType);
        } else if (userType.equals("Assistant")) {
            searchdata.userlbl.setText(userType);
        }
        this.hide();
        searchdata.show();
    }//GEN-LAST:event_searchbActionPerformed

    private void empoperationsbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empoperationsbActionPerformed
        EmployeeOperations empo = new EmployeeOperations();
        this.hide();
        empo.show();
        empo.userlbl.setText("Manager");
    }//GEN-LAST:event_empoperationsbActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ConformDialog.conformLogout(this);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        jButton2.setText("Logout");
        jButton2.setBackground(Color.RED);
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        jButton2.setText("Logged As");
        jButton2.setBackground(new Color(0, 153, 0));
    }//GEN-LAST:event_jButton2MouseExited

    private void searchbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchbMouseEntered
        searchb.setBackground(new Color(144, 238, 144));
    }//GEN-LAST:event_searchbMouseEntered

    private void searchbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchbMouseExited
        searchb.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_searchbMouseExited

    private void createaccountbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createaccountbMouseEntered
        createaccountb.setBackground(new Color(144, 238, 144));
    }//GEN-LAST:event_createaccountbMouseEntered

    private void createaccountbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createaccountbMouseExited
        createaccountb.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_createaccountbMouseExited

    private void empoperationsbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empoperationsbMouseClicked

    }//GEN-LAST:event_empoperationsbMouseClicked

    private void empoperationsbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empoperationsbMouseEntered
        empoperationsb.setBackground(new Color(144, 238, 144));
    }//GEN-LAST:event_empoperationsbMouseEntered

    private void empoperationsbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empoperationsbMouseExited
        empoperationsb.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_empoperationsbMouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        ConformDialog.conformExit();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        ImageIcon icon = new ImageIcon(getClass().getResource("/images/closerl.png"));
        jLabel2.setIcon(icon);
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        ImageIcon icon = new ImageIcon(getClass().getResource("/images/closer.png"));
        jLabel2.setIcon(icon);
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        this.dispose();
        login.show();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        ImageIcon icon = new ImageIcon(getClass().getResource("/images/backl.png"));
        jLabel3.setIcon(icon);
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        ImageIcon icon = new ImageIcon(getClass().getResource("/images/back.png"));
        jLabel3.setIcon(icon);
    }//GEN-LAST:event_jLabel3MouseExited

    private void searchbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchbMouseClicked

    }//GEN-LAST:event_searchbMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton createaccountb;
    protected javax.swing.JButton empoperationsb;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JButton searchb;
    public javax.swing.JLabel titlelbl;
    public javax.swing.JLabel userlbl;
    // End of variables declaration//GEN-END:variables
}
